# syntax=dhi.io/build:2-debian13

name: ArgoCD 3.0.x
image: dhi.io/argocd
variant: runtime
tags:
  - "3.0"
  - 3.0.21
  - 3.0-debian13
  - 3.0.21-debian13
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2025-05-06"
vars:
  ARGOCD_USER_ID: "999"
  COMMIT_SHA: 14cd1c14127fed2c90c7907d0ffcb6d46070c031
  EXPAT_REF: dhi/pkg-expat:2.7.3-debian13@sha256:037c2c61d485b887cadce5dbee99b62c3a25be61082dcc108419c6fd465876e6
  GIT_LFS_REF: dhi/pkg-git-lfs:3.7.1-debian13@sha256:95a5b9cba428a27c209bcbaf27c5c60a5b934bc5663df514d06b5b3834c286f8
  GO_REF: dhi/golang:1.24.11-debian13-dev@sha256:ceccc68aa29c03c808090dc4c6156bebc6d4efaea357281ecde306d6451b7428
  HELM_REF: dhi/helm:3.19.4-debian13@sha256:bba848fa8e45be93921e5e192a6c952a486b40412b59920a42479c642893c81c
  KUSTOMIZE_REF: dhi/kustomize:5.8.0-debian13@sha256:c0c238511832501f81c4494942efc9e1a4ce703002c46162e657535fb866becd
  NODE_REF: dhi/node:20.19.6-debian13-dev@sha256:19d8e0cc9dc874862a8506feb450945ca103c96c3aed97041cf11494f9553907
  SEMVER_MAJOR_MINOR_VERSION: "3.0"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.0.21
  VERSION: 3.0.21
contents:
  packages:
    - '!libelogind0'
    - '!libexpat1'
    - '!mawk'
    - '!original-awk'
    - base-files
    - ca-certificates
    - coreutils
    - dash
    - git
    - gnupg
    - gpg
    - gpg-agent
    - openssh-client
    - tini
    - tzdata
  builds:
    - name: argocd-go
      uses: dhi.io/golang:1.24.11-debian13-dev@sha256:ceccc68aa29c03c808090dc4c6156bebc6d4efaea357281ecde306d6451b7428
      contents:
        packages:
          - curl
          - git
          - gnupg
          - gpg
          - gpg-agent
          - grep
          - gzip
          - openssh-client
          - sed
        files:
          - url: git+https://github.com/argoproj/argo-cd.git#v3.0.21
            checksum: 14cd1c14127fed2c90c7907d0ffcb6d46070c031
            path: /go/src/github.com/argoproj/argo-cd/v3
            spdx:
              name: argocd
              version: 3.0.21
              packages:
                - name: argocd
                  purl: pkg:dhi/argocd@3.0.21
                  license: Apache-2.0
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:20.19.6-debian13-dev@sha256:19d8e0cc9dc874862a8506feb450945ca103c96c3aed97041cf11494f9553907
            includes:
              - opt/nodejs
              - opt/yarn
              - usr/local/bin/node
              - usr/local/bin/yarn
            uid: 0
            gid: 0
          - name: dhi.io/helm:3.19.4-debian13@sha256:bba848fa8e45be93921e5e192a6c952a486b40412b59920a42479c642893c81c
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
          - name: dhi.io/pkg-git-lfs:3.7.1-debian13@sha256:95a5b9cba428a27c209bcbaf27c5c60a5b934bc5663df514d06b5b3834c286f8
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
          - name: dhi.io/kustomize:5.8.0-debian13@sha256:c0c238511832501f81c4494942efc9e1a4ce703002c46162e657535fb866becd
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
      pipeline:
        - name: patch-go (3.0)
          uses: go/bump@v1
          work-dir: /go/src/github.com/argoproj/argo-cd/v3
          with:
            deps:
              - k8s.io/kubernetes@v1.32.10
              - github.com/expr-lang/expr@v1.17.7
              - github.com/cloudflare/circl@v1.6.1
            download: true
        - name: patch-node
          uses: yarn/bump@v1
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          with:
            patches: ${source.dir}/patches/yarn-patches-3.0.json
            skip-yarn-add: true
            yarn-root: .
        - name: patch-node-downgrade
          uses: yarn/patch@v1
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          with:
            downgrade: true
            patches: ${source.dir}/patches/downgrade-yarn-patches.json
            yarn-root: .
        - name: build-ui
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          runs: |
            set -eux -o pipefail

            yarn
            yarn run build
        - name: prepare ui for sbom
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          runs: |
            set -eux -o pipefail

            rm -rf node_modules
            # tsx is included in the dependencies of argocd-ui but should not.
            yarn remove tsx
            # Issue opened: https://github.com/argoproj/argo-cd/issues/24978
            yarn remove react-hot-loader # CVE-2025-57352
            yarn install --production
        - name: ui-sbom
          uses: sbom@v1
          with:
            prefix: argocd-ui
            source: /go/src/github.com/argoproj/argo-cd/v3/ui
        - name: build-backend
          work-dir: /go/src/github.com/argoproj/argo-cd/v3
          runs: |
            set -eux -o pipefail

            KUBECTL_VERSION=$(go list -m k8s.io/client-go | head -n 1 | rev | cut -d' ' -f1 | rev)

            GOLDFLAGS="-extldflags '-static'
                       -X github.com/argoproj/argo-cd/v3/common.version=3.0.21
                       -X github.com/argoproj/argo-cd/v3/common.gitTag=v3.0.21
                       -X github.com/argoproj/argo-cd/v3/common.buildDate=$(date -ud @${SOURCE_DATE_EPOCH} +'%Y-%m-%dT%H:%M:%SZ')
                       -X github.com/argoproj/argo-cd/v3/common.gitCommit=14cd1c14127fed2c90c7907d0ffcb6d46070c031
                       -X github.com/argoproj/argo-cd/v3/common.gitTreeState=clean
                       -X github.com/argoproj/argo-cd/v3/common.kubectlVersion=${KUBECTL_VERSION}"

            CGO_ENABLED=0 GODEBUG="tarinsecurepath=0,zipinsecurepath=0" go build \
              -ldflags "$GOLDFLAGS" \
              -o "${target.dir}/usr/local/bin/argocd" ./cmd
      paths:
        - type: file
          path: /src/patches/yarn-patches-3.0.json
          uid: 0
          gid: 0
          source: image/argocd/patch/yarn-patches-3.0.json
        - type: file
          path: /src/patches/yarn-patches-3.1.json
          uid: 0
          gid: 0
          source: image/argocd/patch/yarn-patches-3.1.json
        - type: file
          path: /src/patches/yarn-patches-3.2.json
          uid: 0
          gid: 0
          source: image/argocd/patch/yarn-patches-3.2.json
        - type: file
          path: /src/patches/downgrade-yarn-patches.json
          uid: 0
          gid: 0
          source: image/argocd/patch/downgrade-yarn-patches.json
      outputs:
        - source: ${target.dir}/usr/local/bin/argocd
          target: /usr/local/bin/argocd
          uid: 0
          gid: 0
        - source: /go/src/github.com/argoproj/argo-cd/v3/hack/gpg-wrapper.sh
          target: /usr/local/bin/gpg-wrapper.sh
          uid: 0
          gid: 0
        - source: /go/src/github.com/argoproj/argo-cd/v3/hack/git-verify-wrapper.sh
          target: /usr/local/bin/git-verify-wrapper.sh
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/argocd
          target: /opt/docker/sbom/argocd
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/argocd-ui
          target: /opt/docker/sbom/argocd-ui
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/pkg-expat:2.7.3-debian13@sha256:037c2c61d485b887cadce5dbee99b62c3a25be61082dcc108419c6fd465876e6
      includes:
        - opt/**
        - usr/**
        - var/lib/dpkg/status.d
      uid: 0
      gid: 0
    - name: dhi.io/helm:3.19.4-debian13@sha256:bba848fa8e45be93921e5e192a6c952a486b40412b59920a42479c642893c81c
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
    - name: dhi.io/pkg-git-lfs:3.7.1-debian13@sha256:95a5b9cba428a27c209bcbaf27c5c60a5b934bc5663df514d06b5b3834c286f8
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
    - name: dhi.io/kustomize:5.8.0-debian13@sha256:c0c238511832501f81c4494942efc9e1a4ce703002c46162e657535fb866becd
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
accounts:
  run-as: "999"
  users:
    - name: argocd
      uid: 999
      gid: 999
  groups:
    - name: argocd
      gid: 999
      members:
        - argocd
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
environment:
  ARGOCD_USER_ID: "999"
paths:
  - type: emptyfile
    path: /app/config/ssh/ssh_known_hosts
    uid: 0
    gid: 0
  - type: directory
    path: /etc/ssh
    uid: 0
    gid: 0
  - type: symlink
    path: /etc/ssh/ssh_known_hosts
    uid: 0
    gid: 0
    source: /app/config/ssh/ssh_known_hosts
  - type: directory
    path: /app/config/gpg/source
    uid: 0
    gid: 0
    recursive: true
  - type: directory
    path: /app/config/gpg/keys
    uid: 999
    gid: 999
    mode: "0700"
    recursive: true
  - type: symlink
    path: /usr/local/bin/argocd-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-repo-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-cmp-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-application-controller
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-dex
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-notifications
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-applicationset-controller
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-k8s-auth
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-commit-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
annotations:
  org.opencontainers.image.description: A minimal ArgoCD image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/bin/tini
  - --
