# syntax=dhi.io/build:2-debian13

name: ArgoCD 3.2.x
image: dhi.io/argocd
variant: runtime
tags:
  - "3"
  - "3.2"
  - 3.2.6
  - 3-debian13
  - 3.2-debian13
  - 3.2.6-debian13
platforms:
  - linux/amd64
  - linux/arm64
dates:
  release: "2025-11-04"
vars:
  ARGOCD_USER_ID: "999"
  COMMIT_SHA: 65b029342d656c03c57f0d0e14433438750c8f5d
  EXPAT_REF: dhi/pkg-expat:2.7.4-debian13@sha256:1a2ba4b5f4c2a647ccec8ee0d2bccba26bc8704c9c89f9940a9cebadc49cb88d
  GIT_LFS_REF: dhi/pkg-git-lfs:3.7.1-debian13@sha256:846b034e46876525dd5a7dfe88a95c25684134633ce6e3e07da3179ecbcb4baf
  GO_REF: dhi/golang:1.25.6-debian13-dev@sha256:1c001ad95e22efced3c6cc3cf875bbfe69c061a383d3b787d4f0a8103e73311c
  HELM_REF: dhi/helm:3.20.0-debian13@sha256:e9c099b887e9e202222b7c0b35c9271ae1085397b0ae4a7ffcc326a998780f23
  KUSTOMIZE_REF: dhi/kustomize:5.8.0-debian13@sha256:5e94c8815243606568915e9a6acedf258aa10ad9f6bb746113c3a04120e59226
  NODE_REF: dhi/node:20.20.0-debian13-dev@sha256:972edf6ec2f55ee956f77b90b3a857e3653530232938c2cb533c263728790dbc
  SEMVER_MAJOR_MINOR_VERSION: "3.2"
  SEMVER_MAJOR_VERSION: "3"
  SEMVER_VERSION: 3.2.6
  VERSION: 3.2.6
contents:
  packages:
    - '!libelogind0'
    - '!libexpat1'
    - '!mawk'
    - '!original-awk'
    - base-files
    - ca-certificates
    - coreutils
    - dash
    - git
    - gnupg
    - gpg
    - gpg-agent
    - openssh-client
    - tini
    - tzdata
  builds:
    - name: argocd-go
      uses: dhi.io/golang:1.25.6-debian13-dev@sha256:1c001ad95e22efced3c6cc3cf875bbfe69c061a383d3b787d4f0a8103e73311c
      contents:
        packages:
          - curl
          - git
          - gnupg
          - gpg
          - gpg-agent
          - grep
          - gzip
          - openssh-client
          - sed
        files:
          - url: git+https://github.com/argoproj/argo-cd.git#v3.2.6
            checksum: 65b029342d656c03c57f0d0e14433438750c8f5d
            path: /go/src/github.com/argoproj/argo-cd/v3
            spdx:
              name: argocd
              version: 3.2.6
              packages:
                - name: argocd
                  purl: pkg:dhi/argocd@3.2.6
                  license: Apache-2.0
            uid: 0
            gid: 0
        artifacts:
          - name: dhi.io/node:20.20.0-debian13-dev@sha256:972edf6ec2f55ee956f77b90b3a857e3653530232938c2cb533c263728790dbc
            includes:
              - opt/nodejs
              - opt/yarn
              - usr/local/bin/node
              - usr/local/bin/yarn
            uid: 0
            gid: 0
          - name: dhi.io/helm:3.20.0-debian13@sha256:e9c099b887e9e202222b7c0b35c9271ae1085397b0ae4a7ffcc326a998780f23
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
          - name: dhi.io/pkg-git-lfs:3.7.1-debian13@sha256:846b034e46876525dd5a7dfe88a95c25684134633ce6e3e07da3179ecbcb4baf
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
          - name: dhi.io/kustomize:5.8.0-debian13@sha256:5e94c8815243606568915e9a6acedf258aa10ad9f6bb746113c3a04120e59226
            includes:
              - opt/**
              - usr/**
            uid: 0
            gid: 0
      pipeline:
        - name: patch-go (3.2)
          uses: go/bump@v1
          work-dir: /go/src/github.com/argoproj/argo-cd/v3
          with:
            deps:
              - k8s.io/kubernetes@v1.34.2
              - github.com/expr-lang/expr@v1.17.7
            download: true
        - name: patch-node
          uses: yarn/bump@v1
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          with:
            patches: ${source.dir}/patches/yarn-patches-3.2.json
            skip-yarn-add: true
            yarn-root: .
        - name: patch-node-downgrade
          uses: yarn/patch@v1
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          with:
            downgrade: true
            patches: ${source.dir}/patches/downgrade-yarn-patches.json
            yarn-root: .
        - name: build-ui
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          runs: |
            set -eux -o pipefail

            yarn
            yarn run build
        - name: prepare ui for sbom
          work-dir: /go/src/github.com/argoproj/argo-cd/v3/ui
          privileged: true
          runs: |
            set -eux -o pipefail

            rm -rf node_modules
            # tsx is included in the dependencies of argocd-ui but should not.
            yarn remove tsx
            # Issue opened: https://github.com/argoproj/argo-cd/issues/24978
            yarn remove react-hot-loader # CVE-2025-57352
            yarn install --production
        - name: ui-sbom
          uses: sbom@v1
          with:
            prefix: argocd-ui
            source: /go/src/github.com/argoproj/argo-cd/v3/ui
        - name: build-backend
          work-dir: /go/src/github.com/argoproj/argo-cd/v3
          runs: |
            set -eux -o pipefail

            KUBECTL_VERSION=$(go list -m k8s.io/client-go | head -n 1 | rev | cut -d' ' -f1 | rev)

            GOLDFLAGS="-extldflags '-static'
                       -X github.com/argoproj/argo-cd/v3/common.version=3.2.6
                       -X github.com/argoproj/argo-cd/v3/common.gitTag=v3.2.6
                       -X github.com/argoproj/argo-cd/v3/common.buildDate=$(date -ud @${SOURCE_DATE_EPOCH} +'%Y-%m-%dT%H:%M:%SZ')
                       -X github.com/argoproj/argo-cd/v3/common.gitCommit=65b029342d656c03c57f0d0e14433438750c8f5d
                       -X github.com/argoproj/argo-cd/v3/common.gitTreeState=clean
                       -X github.com/argoproj/argo-cd/v3/common.kubectlVersion=${KUBECTL_VERSION}"

            CGO_ENABLED=0 GODEBUG="tarinsecurepath=0,zipinsecurepath=0" go build \
              -ldflags "$GOLDFLAGS" \
              -o "${target.dir}/usr/local/bin/argocd" ./cmd
      paths:
        - type: file
          path: /src/patches/yarn-patches-3.0.json
          uid: 0
          gid: 0
          source: image/argocd/patch/yarn-patches-3.0.json
        - type: file
          path: /src/patches/yarn-patches-3.1.json
          uid: 0
          gid: 0
          source: image/argocd/patch/yarn-patches-3.1.json
        - type: file
          path: /src/patches/yarn-patches-3.2.json
          uid: 0
          gid: 0
          source: image/argocd/patch/yarn-patches-3.2.json
        - type: file
          path: /src/patches/downgrade-yarn-patches.json
          uid: 0
          gid: 0
          source: image/argocd/patch/downgrade-yarn-patches.json
      outputs:
        - source: ${target.dir}/usr/local/bin/argocd
          target: /usr/local/bin/argocd
          uid: 0
          gid: 0
        - source: /go/src/github.com/argoproj/argo-cd/v3/hack/gpg-wrapper.sh
          target: /usr/local/bin/gpg-wrapper.sh
          uid: 0
          gid: 0
        - source: /go/src/github.com/argoproj/argo-cd/v3/hack/git-verify-wrapper.sh
          target: /usr/local/bin/git-verify-wrapper.sh
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/argocd
          target: /opt/docker/sbom/argocd
          uid: 0
          gid: 0
        - source: /opt/docker/sbom/argocd-ui
          target: /opt/docker/sbom/argocd-ui
          uid: 0
          gid: 0
  artifacts:
    - name: dhi.io/pkg-expat:2.7.4-debian13@sha256:1a2ba4b5f4c2a647ccec8ee0d2bccba26bc8704c9c89f9940a9cebadc49cb88d
      includes:
        - opt/**
        - usr/**
        - var/lib/dpkg/status.d
      uid: 0
      gid: 0
    - name: dhi.io/helm:3.20.0-debian13@sha256:e9c099b887e9e202222b7c0b35c9271ae1085397b0ae4a7ffcc326a998780f23
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
    - name: dhi.io/pkg-git-lfs:3.7.1-debian13@sha256:846b034e46876525dd5a7dfe88a95c25684134633ce6e3e07da3179ecbcb4baf
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
    - name: dhi.io/kustomize:5.8.0-debian13@sha256:5e94c8815243606568915e9a6acedf258aa10ad9f6bb746113c3a04120e59226
      includes:
        - opt/**
        - usr/**
      uid: 0
      gid: 0
accounts:
  run-as: "999"
  users:
    - name: argocd
      uid: 999
      gid: 999
  groups:
    - name: argocd
      gid: 999
      members:
        - argocd
os-release:
  name: Docker Hardened Images (Debian)
  id: debian
  version-id: "13"
  version-codename: trixie
  pretty-name: Docker Hardened Images/Debian GNU/Linux 13 (trixie)
  home-url: https://docker.com/products/hardened-images/
  bug-report-url: https://docker.com/support/
environment:
  ARGOCD_USER_ID: "999"
paths:
  - type: emptyfile
    path: /app/config/ssh/ssh_known_hosts
    uid: 0
    gid: 0
  - type: directory
    path: /etc/ssh
    uid: 0
    gid: 0
  - type: symlink
    path: /etc/ssh/ssh_known_hosts
    uid: 0
    gid: 0
    source: /app/config/ssh/ssh_known_hosts
  - type: directory
    path: /app/config/gpg/source
    uid: 0
    gid: 0
    recursive: true
  - type: directory
    path: /app/config/gpg/keys
    uid: 999
    gid: 999
    mode: "0700"
    recursive: true
  - type: symlink
    path: /usr/local/bin/argocd-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-repo-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-cmp-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-application-controller
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-dex
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-notifications
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-applicationset-controller
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-k8s-auth
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
  - type: symlink
    path: /usr/local/bin/argocd-commit-server
    uid: 0
    gid: 0
    source: /usr/local/bin/argocd
annotations:
  org.opencontainers.image.description: A minimal ArgoCD image
  org.opencontainers.image.licenses: Apache-2.0
entrypoint:
  - /usr/bin/tini
  - --
